### ISSUE TITLE
Checkout transparente como woocommerce-pagseguro

### ISSUE THREAD

**Issue by slimzc** [claudiosanches/woocommerce-moip#22]
Olá Claudio, Obligado por compartilhar todo esse trabalho com a comunidade.

eu quería saber se dentro da sua estrategia esta fazer o checkout transparente de Moip parecido com o checkout transparente de PagSeguro.
![image](https://cloud.githubusercontent.com/assets/13308499/24888501/54e6ce46-1e3a-11e7-859b-d2aa4263346d.png)
Isto porque (para mim) você da uma melhor experiencia de compra aos clientes, deixando ver tudo em uma pagina (Checkout).

Obrigado!

**Comment by claudiosanches** [comment]
Com a API atual do Moip que esta sendo usada no plugin não é possível, por isso que não fiz dessa forma.
Mas estou trabalhando em uma versão nova com a nova API do do Moip onde isso será possível.

**Comment by digomiero** [comment]
Boa noite, Claudio.
Sei que você tem 259 mil projetos beneficentes em prol da comunidade, então não entenda como nenhum tipo de cobrança, apenas como uma dúvida honesta mesmo: Essa atualização pra nova API ainda tá nos planos?
Um abraço!
